# -*- coding: utf-8 -*-
"""ASSIGNMENT 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10LngDY4NgX7qLtyYASz_gt4fWvWCd_TO
"""

celsius=float(input())
fahrenheit=celsius*1.8+32
print("after converting to fahrenheit",fahrenheit)

width=17
height=12.0
a=width//2
b=width//2.0
c=height/3
d=1+2*5
print(a)
print(b)
print(c)
print(d)
print(type(a))
print(type(b))
print(type(c))
print(type(d))

a=int(input())
b=int(input())
c=a+b
print(c)

hours=float(input("enter hours:"))
rate=float(input("enter rate:"))
pay=hours*rate
print("pay=",pay)

a=input("enter a name")
print(a,"welcome")