# -*- coding: utf-8 -*-
"""ASSIGNMENT 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M7XRHDLjzA6aolWihr7ZmB32k_uWA0R6
"""

a=int(input())
b=int(input())
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

p=int(input())
t=int(input())
r=int(input())
si=(p*t*r)/100
print("the si is",si)

r=int(input())
area=3.14*(r**2)
print("the area is",area)

b=int(input())
h=int(input())
area=(0.5*b*h)
print("the area of triangle",area)

celsius=float(input())
fahrenhiet=(celsius*1.8)+32
print("the fahrenhiet is",fahrenhiet)

l=int(input())
b=int(input())
area=l*b
print("the area of rectangle is",area)

s=int(input())
peri=4*s
print("the perimeter is",peri)

r=int(input())
cf=2*3.14*r
print("the cf is",cf)

a=int(input())
b=int(input())
print("before swapping",a,b)
temp=a
a=b
b=temp
print("after swapping",a,b)